import = [
"~/.config/alacritty/themes/gnome_terminal.toml"
]

#[shell]
#program = "/bin/zsh"
#args = ["-l"]

[window]
opacity = 0.9

[font]
normal = { family = "JetBrains Mono", style = "Regular"}
bold = { style = "Bold"}
italic = { style = "Italic"}
bold_italic = { style = "Bold Italic"}
size = 12.0

[colors]
draw_bold_text_with_bright_colors = true
